--Goran Somic CSC 453

DROP TABLE Loan;

CREATE TABLE Loan (
    Amount NUMBER(5),
    Loan_Date DATE,
    Loan_Title VARCHAR(75),
    Risk_Score NUMBER(3),
    Debt_To_Income_Ratio FLOAT,
    Zipcode NUMBER(5),
    State VARCHAR(2),
    Employment_Length NUMBER(2),
    Policy_Code NUMBER(1)
    );
    
SET DEFINE OFF

INSERT INTO LOAN (AMOUNT, LOAN_DATE, LOAN_TITLE, RISK_SCORE, DEBT_TO_INCOME_RATIO, ZIPCODE, STATE, EMPLOYMENT_LENGTH, POLICY_CODE) 
VALUES (1000, to_date('5/26/07', 'MM/DD/RRRR'), 'Wedding Covered but No Honeymoon', 693, 10, 48127, 'NM', 4, 0);

INSERT INTO LOAN (AMOUNT, LOAN_DATE, LOAN_TITLE, RISK_SCORE, DEBT_TO_INCOME_RATIO, ZIPCODE, STATE, EMPLOYMENT_LENGTH, POLICY_CODE) 
VALUES (1000, to_date('5/26/07', 'MM/DD/RRRR'), 'Consolidating Debt', 703, 10, 1027, 'MA', 1, 0);

INSERT INTO LOAN (AMOUNT, LOAN_DATE, LOAN_TITLE, RISK_SCORE, DEBT_TO_INCOME_RATIO, ZIPCODE, STATE, EMPLOYMENT_LENGTH, POLICY_CODE) 
VALUES (11000, to_date('5/27/07', 'MM/DD/RRRR'), 'Want to consolidate my debt', 715, 10, 21227, 'MD', 1, 0);

INSERT INTO LOAN (AMOUNT, LOAN_DATE, LOAN_TITLE, RISK_SCORE, DEBT_TO_INCOME_RATIO, ZIPCODE, STATE, EMPLOYMENT_LENGTH, POLICY_CODE) 
VALUES (6000, to_date('5/27/07', 'MM/DD/RRRR'), 'waksman', 698, 38.64, 1727, 'MA', 1, 0);

INSERT INTO LOAN (AMOUNT, LOAN_DATE, LOAN_TITLE, RISK_SCORE, DEBT_TO_INCOME_RATIO, ZIPCODE, STATE, EMPLOYMENT_LENGTH, POLICY_CODE) 
VALUES (1500, to_date('5/27/07', 'MM/DD/RRRR'), 'mdrigo', 509, 9.43, 20927, 'MD', 1, 0);

INSERT INTO LOAN (AMOUNT, LOAN_DATE, LOAN_TITLE, RISK_SCORE, DEBT_TO_INCOME_RATIO, ZIPCODE, STATE, EMPLOYMENT_LENGTH, POLICY_CODE) 
VALUES (15000, to_date('5/27/07', 'MM/DD/RRRR'), 'Trinfiniti', 645, 0, 10527, 'NY', 3, 0);

INSERT INTO LOAN (AMOUNT, LOAN_DATE, LOAN_TITLE, RISK_SCORE, DEBT_TO_INCOME_RATIO, ZIPCODE, STATE, EMPLOYMENT_LENGTH, POLICY_CODE) 
VALUES (10000, to_date('5/27/07', 'MM/DD/RRRR'), 'NOTIFYi Inc', 693, 10, 21027, 'MD', 1, 0);

INSERT INTO LOAN (AMOUNT, LOAN_DATE, LOAN_TITLE, RISK_SCORE, DEBT_TO_INCOME_RATIO, ZIPCODE, STATE, EMPLOYMENT_LENGTH, POLICY_CODE) 
VALUES (3900, to_date('5/27/07', 'MM/DD/RRRR'), 'For Justin.', 700, 10, 46927, 'IN', 2, 0);

INSERT INTO LOAN (AMOUNT, LOAN_DATE, LOAN_TITLE, RISK_SCORE, DEBT_TO_INCOME_RATIO, ZIPCODE, STATE, EMPLOYMENT_LENGTH, POLICY_CODE) 
VALUES (3000, to_date('5/28/07', 'MM/DD/RRRR'), 'title?', 694, 10, 80827, 'CO', 4, 0);

INSERT INTO LOAN (AMOUNT, LOAN_DATE, LOAN_TITLE, RISK_SCORE, DEBT_TO_INCOME_RATIO, ZIPCODE, STATE, EMPLOYMENT_LENGTH, POLICY_CODE) 
VALUES (2500, to_date('5/28/07', 'MM/DD/RRRR'), 'timgerst', 573, 11.76, 40727, 'KY', 4, 0);

INSERT INTO LOAN (AMOUNT, LOAN_DATE, LOAN_TITLE, RISK_SCORE, DEBT_TO_INCOME_RATIO, ZIPCODE, STATE, EMPLOYMENT_LENGTH, POLICY_CODE) 
VALUES (3900, to_date('5/28/07', 'MM/DD/RRRR'), 'need to consolidate', 710, 10, 70527, 'LA', 3, 0);

INSERT INTO LOAN (AMOUNT, LOAN_DATE, LOAN_TITLE, RISK_SCORE, DEBT_TO_INCOME_RATIO, ZIPCODE, STATE, EMPLOYMENT_LENGTH, POLICY_CODE) 
VALUES (1000, to_date('5/28/07', 'MM/DD/RRRR'), 'sixstrings', 680, 10, 42427, 'KY', 1, 0);

INSERT INTO LOAN (AMOUNT, LOAN_DATE, LOAN_TITLE, RISK_SCORE, DEBT_TO_INCOME_RATIO, ZIPCODE, STATE, EMPLOYMENT_LENGTH, POLICY_CODE) 
VALUES (3000, to_date('5/28/07', 'MM/DD/RRRR'), 'bmoore5110', 688, 10, 19027, 'PA', 1, 0);

INSERT INTO LOAN (AMOUNT, LOAN_DATE, LOAN_TITLE, RISK_SCORE, DEBT_TO_INCOME_RATIO, ZIPCODE, STATE, EMPLOYMENT_LENGTH, POLICY_CODE) 
VALUES (1500, to_date('5/28/07', 'MM/DD/RRRR'), 'MHarkins', 704, 10, 18927, 'PA', 3, 0);

INSERT INTO LOAN (AMOUNT, LOAN_DATE, LOAN_TITLE, RISK_SCORE, DEBT_TO_INCOME_RATIO, ZIPCODE, STATE, EMPLOYMENT_LENGTH, POLICY_CODE) 
VALUES (1000, to_date('5/28/07', 'MM/DD/RRRR'), 'Moving', 694, 10, 35427, 'AL', 1, 0);

INSERT INTO LOAN (AMOUNT, LOAN_DATE, LOAN_TITLE, RISK_SCORE, DEBT_TO_INCOME_RATIO, ZIPCODE, STATE, EMPLOYMENT_LENGTH, POLICY_CODE) 
VALUES (8000, to_date('5/28/07', 'MM/DD/RRRR'), 'Recent College Grad Wants to Pay Off CCs', 708, 10, 37427, 'TN', 1, 0);

INSERT INTO LOAN (AMOUNT, LOAN_DATE, LOAN_TITLE, RISK_SCORE, DEBT_TO_INCOME_RATIO, ZIPCODE, STATE, EMPLOYMENT_LENGTH, POLICY_CODE) 
VALUES (12000, to_date('5/29/07', 'MM/DD/RRRR'), 'FoundersCafe.com', 685, 10, 77027, 'TX', 3, 0);

INSERT INTO LOAN (AMOUNT, LOAN_DATE, LOAN_TITLE, RISK_SCORE, DEBT_TO_INCOME_RATIO, ZIPCODE, STATE, EMPLOYMENT_LENGTH, POLICY_CODE) 
VALUES (1000, to_date('5/29/07', 'MM/DD/RRRR'), 'UChicago2004', 698, 10, 20727, 'MD', 3, 0);

INSERT INTO LOAN (AMOUNT, LOAN_DATE, LOAN_TITLE, RISK_SCORE, DEBT_TO_INCOME_RATIO, ZIPCODE, STATE, EMPLOYMENT_LENGTH, POLICY_CODE) 
VALUES (15000, to_date('5/29/07', 'MM/DD/RRRR'), 'Cancer is Killing My Credit', 680, 10, 43227, 'OH', 1, 0);

INSERT INTO LOAN (AMOUNT, LOAN_DATE, LOAN_TITLE, RISK_SCORE, DEBT_TO_INCOME_RATIO, ZIPCODE, STATE, EMPLOYMENT_LENGTH, POLICY_CODE) 
VALUES (5000, to_date('5/29/07', 'MM/DD/RRRR'), '2006-2007 College Debt Loan', 680, 10, 1127, 'MA', 1, 0);

INSERT INTO LOAN (AMOUNT, LOAN_DATE, LOAN_TITLE, RISK_SCORE, DEBT_TO_INCOME_RATIO, ZIPCODE, STATE, EMPLOYMENT_LENGTH, POLICY_CODE) 
VALUES (15000, to_date('5/29/07', 'MM/DD/RRRR'), 'twbmc', 712, 10, 77327, 'TX', 1, 0);

INSERT INTO LOAN (AMOUNT, LOAN_DATE, LOAN_TITLE, RISK_SCORE, DEBT_TO_INCOME_RATIO, ZIPCODE, STATE, EMPLOYMENT_LENGTH, POLICY_CODE) 
VALUES (5000, to_date('5/29/07', 'MM/DD/RRRR'), 'Bills and Vacation', 704, 10, 21227, 'MD', 1, 0);

INSERT INTO LOAN (AMOUNT, LOAN_DATE, LOAN_TITLE, RISK_SCORE, DEBT_TO_INCOME_RATIO, ZIPCODE, STATE, EMPLOYMENT_LENGTH, POLICY_CODE) 
VALUES (4950, to_date('5/29/07', 'MM/DD/RRRR'), 'Vehicle Purchase/Used Auto', 693, 10, 22027, 'VA', 2, 0);

INSERT INTO LOAN (AMOUNT, LOAN_DATE, LOAN_TITLE, RISK_SCORE, DEBT_TO_INCOME_RATIO, ZIPCODE, STATE, EMPLOYMENT_LENGTH, POLICY_CODE) 
VALUES (6100, to_date('5/29/07', 'MM/DD/RRRR'), 'thejanman', 684, 24.69, 45327, 'OH', 2, 0);

INSERT INTO LOAN (AMOUNT, LOAN_DATE, LOAN_TITLE, RISK_SCORE, DEBT_TO_INCOME_RATIO, ZIPCODE, STATE, EMPLOYMENT_LENGTH, POLICY_CODE) 
VALUES (12000, to_date('5/29/07', 'MM/DD/RRRR'), 'Finish Off College', 704, 10, 46227, 'IN', 2, 0);

INSERT INTO LOAN (AMOUNT, LOAN_DATE, LOAN_TITLE, RISK_SCORE, DEBT_TO_INCOME_RATIO, ZIPCODE, STATE, EMPLOYMENT_LENGTH, POLICY_CODE) 
VALUES (25000, to_date('5/29/07', 'MM/DD/RRRR'), 'Phuocpnn', 686, 10, 63127, 'MO', 1, 0);

INSERT INTO LOAN (AMOUNT, LOAN_DATE, LOAN_TITLE, RISK_SCORE, DEBT_TO_INCOME_RATIO, ZIPCODE, STATE, EMPLOYMENT_LENGTH, POLICY_CODE) 
VALUES (15000, to_date('5/29/07', 'MM/DD/RRRR'), 'Established borrower consolodating debt', 698, 15.56, 55927, 'MN', 1, 0);

INSERT INTO LOAN (AMOUNT, LOAN_DATE, LOAN_TITLE, RISK_SCORE, DEBT_TO_INCOME_RATIO, ZIPCODE, STATE, EMPLOYMENT_LENGTH, POLICY_CODE) 
VALUES (5000, to_date('5/29/07', 'MM/DD/RRRR'), 'mainmanandy', 719, 10, 45727, 'OH', 1, 0);

INSERT INTO LOAN (AMOUNT, LOAN_DATE, LOAN_TITLE, RISK_SCORE, DEBT_TO_INCOME_RATIO, ZIPCODE, STATE, EMPLOYMENT_LENGTH, POLICY_CODE) 
VALUES (10000, to_date('5/30/07', 'MM/DD/RRRR'), 'Jaguar10301', 602, 2.25, 22127, 'VA', 1, 0);

INSERT INTO LOAN (AMOUNT, LOAN_DATE, LOAN_TITLE, RISK_SCORE, DEBT_TO_INCOME_RATIO, ZIPCODE, STATE, EMPLOYMENT_LENGTH, POLICY_CODE) 
VALUES (10000, to_date('5/30/07', 'MM/DD/RRRR'), 'rpinho78', 475, 21.77, 6127, 'CT', 1, 0);

INSERT INTO LOAN (AMOUNT, LOAN_DATE, LOAN_TITLE, RISK_SCORE, DEBT_TO_INCOME_RATIO, ZIPCODE, STATE, EMPLOYMENT_LENGTH, POLICY_CODE) 
VALUES (1000, to_date('5/30/07', 'MM/DD/RRRR'), 'ashtru', 695, 0, 44327, 'OH', 1, 0);

INSERT INTO LOAN (AMOUNT, LOAN_DATE, LOAN_TITLE, RISK_SCORE, DEBT_TO_INCOME_RATIO, ZIPCODE, STATE, EMPLOYMENT_LENGTH, POLICY_CODE) 
VALUES (4000, to_date('5/30/07', 'MM/DD/RRRR'), 'sparks', 671, 36.8, 63027, 'MO', 1, 0);

INSERT INTO LOAN (AMOUNT, LOAN_DATE, LOAN_TITLE, RISK_SCORE, DEBT_TO_INCOME_RATIO, ZIPCODE, STATE, EMPLOYMENT_LENGTH, POLICY_CODE) 
VALUES (7000, to_date('5/30/07', 'MM/DD/RRRR'), 'big fat lender', 638, 17.73, 94127, 'CA', 1, 0);

INSERT INTO LOAN (AMOUNT, LOAN_DATE, LOAN_TITLE, RISK_SCORE, DEBT_TO_INCOME_RATIO, ZIPCODE, STATE, EMPLOYMENT_LENGTH, POLICY_CODE) 
VALUES (25000, to_date('5/30/07', 'MM/DD/RRRR'), 'toeeeekne', 671, 4.5, 48327, 'FL', 2, 0);

INSERT INTO LOAN (AMOUNT, LOAN_DATE, LOAN_TITLE, RISK_SCORE, DEBT_TO_INCOME_RATIO, ZIPCODE, STATE, EMPLOYMENT_LENGTH, POLICY_CODE) 
VALUES (1000, to_date('5/30/07', 'MM/DD/RRRR'), 'stnthoma22', 429, 15.92, 46227, 'IN', 2, 0);

INSERT INTO LOAN (AMOUNT, LOAN_DATE, LOAN_TITLE, RISK_SCORE, DEBT_TO_INCOME_RATIO, ZIPCODE, STATE, EMPLOYMENT_LENGTH, POLICY_CODE) 
VALUES (6500, to_date('5/30/07', 'MM/DD/RRRR'), 'natbunn', 632, 12.98, 77327, 'TX', 1, 0);

INSERT INTO LOAN (AMOUNT, LOAN_DATE, LOAN_TITLE, RISK_SCORE, DEBT_TO_INCOME_RATIO, ZIPCODE, STATE, EMPLOYMENT_LENGTH, POLICY_CODE) 
VALUES (2000, to_date('5/30/07', 'MM/DD/RRRR'), 'SGearhart1381', 579, 32.64, 65827, 'MO', 1, 0);

INSERT INTO LOAN (AMOUNT, LOAN_DATE, LOAN_TITLE, RISK_SCORE, DEBT_TO_INCOME_RATIO, ZIPCODE, STATE, EMPLOYMENT_LENGTH, POLICY_CODE) 
VALUES (15000, to_date('5/30/07', 'MM/DD/RRRR'), '2dozen', 474, 1.55, 45327, 'OH', 4, 0);

INSERT INTO LOAN (AMOUNT, LOAN_DATE, LOAN_TITLE, RISK_SCORE, DEBT_TO_INCOME_RATIO, ZIPCODE, STATE, EMPLOYMENT_LENGTH, POLICY_CODE) 
VALUES (6000, to_date('5/30/07', 'MM/DD/RRRR'), 'Good Heart Bad Credit!', 463, 12.34, 95327, 'CA', 1, 0);

INSERT INTO LOAN (AMOUNT, LOAN_DATE, LOAN_TITLE, RISK_SCORE, DEBT_TO_INCOME_RATIO, ZIPCODE, STATE, EMPLOYMENT_LENGTH, POLICY_CODE) 
VALUES (2500, to_date('5/31/07', 'MM/DD/RRRR'), 'mbcoon', 593, 18.43, 79027, 'TX', 1, 0);

INSERT INTO LOAN (AMOUNT, LOAN_DATE, LOAN_TITLE, RISK_SCORE, DEBT_TO_INCOME_RATIO, ZIPCODE, STATE, EMPLOYMENT_LENGTH, POLICY_CODE) 
VALUES (12500, to_date('5/31/07', 'MM/DD/RRRR'), 'boardwalk', 578, 31.82, 77527, 'TX', 9, 0);

INSERT INTO LOAN (AMOUNT, LOAN_DATE, LOAN_TITLE, RISK_SCORE, DEBT_TO_INCOME_RATIO, ZIPCODE, STATE, EMPLOYMENT_LENGTH, POLICY_CODE) 
VALUES (3000, to_date('5/31/07', 'MM/DD/RRRR'), 'danthe83', 536, 0, 55127, 'MN', 1, 0);

INSERT INTO LOAN (AMOUNT, LOAN_DATE, LOAN_TITLE, RISK_SCORE, DEBT_TO_INCOME_RATIO, ZIPCODE, STATE, EMPLOYMENT_LENGTH, POLICY_CODE) 
VALUES (7500, to_date('5/31/07', 'MM/DD/RRRR'), 'maryk2001', 524, 61.47, 31627, 'GA', 5, 0);

INSERT INTO LOAN (AMOUNT, LOAN_DATE, LOAN_TITLE, RISK_SCORE, DEBT_TO_INCOME_RATIO, ZIPCODE, STATE, EMPLOYMENT_LENGTH, POLICY_CODE) 
VALUES (5000, to_date('5/31/07', 'MM/DD/RRRR'), 'ppatti113', 520, 8.93, 2427, 'MA', 1, 0);

INSERT INTO LOAN (AMOUNT, LOAN_DATE, LOAN_TITLE, RISK_SCORE, DEBT_TO_INCOME_RATIO, ZIPCODE, STATE, EMPLOYMENT_LENGTH, POLICY_CODE) 
VALUES (5000, to_date('5/31/07', 'MM/DD/RRRR'), 'spidermonkey07', 0, 6, 44827, 'OH', 1, 0);

INSERT INTO LOAN (AMOUNT, LOAN_DATE, LOAN_TITLE, RISK_SCORE, DEBT_TO_INCOME_RATIO, ZIPCODE, STATE, EMPLOYMENT_LENGTH, POLICY_CODE) 
VALUES (4000, to_date('5/31/07', 'MM/DD/RRRR'), 'brock1jd', 658, 43.8, 48027, 'MN', 1, 0);

INSERT INTO LOAN (AMOUNT, LOAN_DATE, LOAN_TITLE, RISK_SCORE, DEBT_TO_INCOME_RATIO, ZIPCODE, STATE, EMPLOYMENT_LENGTH, POLICY_CODE) 
VALUES (1000, to_date('5/31/07', 'MM/DD/RRRR'), 'jprice1542', 0, 4.61, 37327, 'TN', 1, 0);

INSERT INTO LOAN (AMOUNT, LOAN_DATE, LOAN_TITLE, RISK_SCORE, DEBT_TO_INCOME_RATIO, ZIPCODE, STATE, EMPLOYMENT_LENGTH, POLICY_CODE) 
VALUES (5000, to_date('5/31/07', 'MM/DD/RRRR'), 'mashowar', 492, 15.73, 47427, 'IN', 4, 0);

INSERT INTO LOAN (AMOUNT, LOAN_DATE, LOAN_TITLE, RISK_SCORE, DEBT_TO_INCOME_RATIO, ZIPCODE, STATE, EMPLOYMENT_LENGTH, POLICY_CODE) 
VALUES (1000, to_date('5/31/07', 'MM/DD/RRRR'), 'jaynesweet', 581, 28.04, 68127, 'NE', 2, 0);

INSERT INTO LOAN (AMOUNT, LOAN_DATE, LOAN_TITLE, RISK_SCORE, DEBT_TO_INCOME_RATIO, ZIPCODE, STATE, EMPLOYMENT_LENGTH, POLICY_CODE) 
VALUES (1000, to_date('6/1/07', 'MM/DD/RRRR'), 'memorial', 543, 41.35, 32827, 'FL', 2, 0);

INSERT INTO LOAN (AMOUNT, LOAN_DATE, LOAN_TITLE, RISK_SCORE, DEBT_TO_INCOME_RATIO, ZIPCODE, STATE, EMPLOYMENT_LENGTH, POLICY_CODE) 
VALUES (6025, to_date('6/1/07', 'MM/DD/RRRR'), 'Fleurdetragedie', 660, 69.84, 30127, 'GA', 2, 0);

INSERT INTO LOAN (AMOUNT, LOAN_DATE, LOAN_TITLE, RISK_SCORE, DEBT_TO_INCOME_RATIO, ZIPCODE, STATE, EMPLOYMENT_LENGTH, POLICY_CODE) 
VALUES (10000, to_date('6/1/07', 'MM/DD/RRRR'), 'jfirson', 503, 61.07, 66827, 'KS', 1, 0);

INSERT INTO LOAN (AMOUNT, LOAN_DATE, LOAN_TITLE, RISK_SCORE, DEBT_TO_INCOME_RATIO, ZIPCODE, STATE, EMPLOYMENT_LENGTH, POLICY_CODE) 
VALUES (3000, to_date('6/1/07', 'MM/DD/RRRR'), 'cdc', 556, 20.91, 78627, 'TX', 1, 0);

INSERT INTO LOAN (AMOUNT, LOAN_DATE, LOAN_TITLE, RISK_SCORE, DEBT_TO_INCOME_RATIO, ZIPCODE, STATE, EMPLOYMENT_LENGTH, POLICY_CODE) 
VALUES (10000, to_date('6/1/07', 'MM/DD/RRRR'), 'katiemass', 480, 8.7, 45227, 'OH', 1, 0);

INSERT INTO LOAN (AMOUNT, LOAN_DATE, LOAN_TITLE, RISK_SCORE, DEBT_TO_INCOME_RATIO, ZIPCODE, STATE, EMPLOYMENT_LENGTH, POLICY_CODE) 
VALUES (2100, to_date('6/1/07', 'MM/DD/RRRR'), 'A clean sweep before buying a new house', 684, 10, 20827, 'MD', 1, 0);

INSERT INTO LOAN (AMOUNT, LOAN_DATE, LOAN_TITLE, RISK_SCORE, DEBT_TO_INCOME_RATIO, ZIPCODE, STATE, EMPLOYMENT_LENGTH, POLICY_CODE) 
VALUES (5000, to_date('6/1/07', 'MM/DD/RRRR'), 'kennysack', 592, 53.76, 47727, 'IN', 1, 0);

INSERT INTO LOAN (AMOUNT, LOAN_DATE, LOAN_TITLE, RISK_SCORE, DEBT_TO_INCOME_RATIO, ZIPCODE, STATE, EMPLOYMENT_LENGTH, POLICY_CODE) 
VALUES (10000, to_date('6/1/07', 'MM/DD/RRRR'), 'dreamerabove', 600, 3.84, 2127, 'MA', 1, 0);

INSERT INTO LOAN (AMOUNT, LOAN_DATE, LOAN_TITLE, RISK_SCORE, DEBT_TO_INCOME_RATIO, ZIPCODE, STATE, EMPLOYMENT_LENGTH, POLICY_CODE) 
VALUES (1200, to_date('6/1/07', 'MM/DD/RRRR'), 'jflack', 524, 0, 72027, 'AR', 4, 0);

INSERT INTO LOAN (AMOUNT, LOAN_DATE, LOAN_TITLE, RISK_SCORE, DEBT_TO_INCOME_RATIO, ZIPCODE, STATE, EMPLOYMENT_LENGTH, POLICY_CODE) 
VALUES (4000, to_date('6/1/07', 'MM/DD/RRRR'), 'ceodiva', 460, 0, 30227, 'GA', 1, 0);

INSERT INTO LOAN (AMOUNT, LOAN_DATE, LOAN_TITLE, RISK_SCORE, DEBT_TO_INCOME_RATIO, ZIPCODE, STATE, EMPLOYMENT_LENGTH, POLICY_CODE) 
VALUES (15000, to_date('6/1/07', 'MM/DD/RRRR'), 'joelforeman', 654, 27.48, 32827, 'FL', 2, 0);

INSERT INTO LOAN (AMOUNT, LOAN_DATE, LOAN_TITLE, RISK_SCORE, DEBT_TO_INCOME_RATIO, ZIPCODE, STATE, EMPLOYMENT_LENGTH, POLICY_CODE) 
VALUES (1000, to_date('6/1/07', 'MM/DD/RRRR'), 'auburnmk23', 486, 12.4, 36827, 'AL', 1, 0);

INSERT INTO LOAN (AMOUNT, LOAN_DATE, LOAN_TITLE, RISK_SCORE, DEBT_TO_INCOME_RATIO, ZIPCODE, STATE, EMPLOYMENT_LENGTH, POLICY_CODE) 
VALUES (2500, to_date('6/1/07', 'MM/DD/RRRR'), 'Scott Stowe', 520, 13.1, 46027, 'IN', 1, 0);

INSERT INTO LOAN (AMOUNT, LOAN_DATE, LOAN_TITLE, RISK_SCORE, DEBT_TO_INCOME_RATIO, ZIPCODE, STATE, EMPLOYMENT_LENGTH, POLICY_CODE) 
VALUES (5000, to_date('6/1/07', 'MM/DD/RRRR'), 'iamheatherleigh', 0, 0, 40527, 'KY', 5, 0);

INSERT INTO LOAN (AMOUNT, LOAN_DATE, LOAN_TITLE, RISK_SCORE, DEBT_TO_INCOME_RATIO, ZIPCODE, STATE, EMPLOYMENT_LENGTH, POLICY_CODE) 
VALUES (2500, to_date('6/1/07', 'MM/DD/RRRR'), 'Paying for college', 547, 29.16, 33127, 'FL', 1, 0);

INSERT INTO LOAN (AMOUNT, LOAN_DATE, LOAN_TITLE, RISK_SCORE, DEBT_TO_INCOME_RATIO, ZIPCODE, STATE, EMPLOYMENT_LENGTH, POLICY_CODE) 
VALUES (1000, to_date('6/1/07', 'MM/DD/RRRR'), 'alivrum', 454, 7.68, 43427, 'OH', 1, 0);

INSERT INTO LOAN (AMOUNT, LOAN_DATE, LOAN_TITLE, RISK_SCORE, DEBT_TO_INCOME_RATIO, ZIPCODE, STATE, EMPLOYMENT_LENGTH, POLICY_CODE) 
VALUES (5000, to_date('6/2/07', 'MM/DD/RRRR'), 'wbnd44', 509, 20, 43627, 'OH', 1, 0);

INSERT INTO LOAN (AMOUNT, LOAN_DATE, LOAN_TITLE, RISK_SCORE, DEBT_TO_INCOME_RATIO, ZIPCODE, STATE, EMPLOYMENT_LENGTH, POLICY_CODE) 
VALUES (5000, to_date('6/2/07', 'MM/DD/RRRR'), 'skyydogg', 0, 0, 53527, 'WI', 1, 0);

INSERT INTO LOAN (AMOUNT, LOAN_DATE, LOAN_TITLE, RISK_SCORE, DEBT_TO_INCOME_RATIO, ZIPCODE, STATE, EMPLOYMENT_LENGTH, POLICY_CODE) 
VALUES (1500, to_date('6/2/07', 'MM/DD/RRRR'), 'Svengar7', 665, 0, 19127, 'PA', 1, 0);

INSERT INTO LOAN (AMOUNT, LOAN_DATE, LOAN_TITLE, RISK_SCORE, DEBT_TO_INCOME_RATIO, ZIPCODE, STATE, EMPLOYMENT_LENGTH, POLICY_CODE) 
VALUES (1000, to_date('6/2/07', 'MM/DD/RRRR'), 'sopinksolovely', 454, 11.12, 11327, 'NY', 2, 0);

INSERT INTO LOAN (AMOUNT, LOAN_DATE, LOAN_TITLE, RISK_SCORE, DEBT_TO_INCOME_RATIO, ZIPCODE, STATE, EMPLOYMENT_LENGTH, POLICY_CODE) 
VALUES (1000, to_date('6/2/07', 'MM/DD/RRRR'), 'angelbabe', 561, 1.07, 10427, 'NY', 1, 0);

INSERT INTO LOAN (AMOUNT, LOAN_DATE, LOAN_TITLE, RISK_SCORE, DEBT_TO_INCOME_RATIO, ZIPCODE, STATE, EMPLOYMENT_LENGTH, POLICY_CODE) 
VALUES (8000, to_date('6/2/07', 'MM/DD/RRRR'), 'K9Genetics', 565, 11.67, 85227, 'AZ', 1, 0);

INSERT INTO LOAN (AMOUNT, LOAN_DATE, LOAN_TITLE, RISK_SCORE, DEBT_TO_INCOME_RATIO, ZIPCODE, STATE, EMPLOYMENT_LENGTH, POLICY_CODE) 
VALUES (3500, to_date('6/2/07', 'MM/DD/RRRR'), 'zminer', 479, 1.73, 80527, 'CO', 1, 0);

INSERT INTO LOAN (AMOUNT, LOAN_DATE, LOAN_TITLE, RISK_SCORE, DEBT_TO_INCOME_RATIO, ZIPCODE, STATE, EMPLOYMENT_LENGTH, POLICY_CODE) 
VALUES (2500, to_date('6/2/07', 'MM/DD/RRRR'), 'moecheeks21', 444, 0, 67427, 'KS', 1, 0);

INSERT INTO LOAN (AMOUNT, LOAN_DATE, LOAN_TITLE, RISK_SCORE, DEBT_TO_INCOME_RATIO, ZIPCODE, STATE, EMPLOYMENT_LENGTH, POLICY_CODE) 
VALUES (25000, to_date('6/2/07', 'MM/DD/RRRR'), 'Lilly', 549, 20.06, 85227, 'AZ', 4, 0);

INSERT INTO LOAN (AMOUNT, LOAN_DATE, LOAN_TITLE, RISK_SCORE, DEBT_TO_INCOME_RATIO, ZIPCODE, STATE, EMPLOYMENT_LENGTH, POLICY_CODE) 
VALUES (4500, to_date('6/2/07', 'MM/DD/RRRR'), 'QuisyFBaby', 599, 16.8, 21227, 'MD', 1, 0);

INSERT INTO LOAN (AMOUNT, LOAN_DATE, LOAN_TITLE, RISK_SCORE, DEBT_TO_INCOME_RATIO, ZIPCODE, STATE, EMPLOYMENT_LENGTH, POLICY_CODE) 
VALUES (2000, to_date('6/3/07', 'MM/DD/RRRR'), 'thesassaman', 650, 0, 98027, 'WA', 1, 0);

INSERT INTO LOAN (AMOUNT, LOAN_DATE, LOAN_TITLE, RISK_SCORE, DEBT_TO_INCOME_RATIO, ZIPCODE, STATE, EMPLOYMENT_LENGTH, POLICY_CODE) 
VALUES (10000, to_date('6/3/07', 'MM/DD/RRRR'), 'regan117', 607, 23.1, 18227, 'PA', 1, 0);

INSERT INTO LOAN (AMOUNT, LOAN_DATE, LOAN_TITLE, RISK_SCORE, DEBT_TO_INCOME_RATIO, ZIPCODE, STATE, EMPLOYMENT_LENGTH, POLICY_CODE) 
VALUES (3500, to_date('6/3/07', 'MM/DD/RRRR'), 'manx203', 0, 0, 15127, 'PA', 1, 0);

INSERT INTO LOAN (AMOUNT, LOAN_DATE, LOAN_TITLE, RISK_SCORE, DEBT_TO_INCOME_RATIO, ZIPCODE, STATE, EMPLOYMENT_LENGTH, POLICY_CODE) 
VALUES (5000, to_date('6/3/07', 'MM/DD/RRRR'), 'eswist', 419, 3.48, 77327, 'TX', 1, 0);

INSERT INTO LOAN (AMOUNT, LOAN_DATE, LOAN_TITLE, RISK_SCORE, DEBT_TO_INCOME_RATIO, ZIPCODE, STATE, EMPLOYMENT_LENGTH, POLICY_CODE) 
VALUES (11000, to_date('6/3/07', 'MM/DD/RRRR'), 'Consolidate Prosper', 758, 37.3, 97227, 'OR', 1, 0);

INSERT INTO LOAN (AMOUNT, LOAN_DATE, LOAN_TITLE, RISK_SCORE, DEBT_TO_INCOME_RATIO, ZIPCODE, STATE, EMPLOYMENT_LENGTH, POLICY_CODE) 
VALUES (1500, to_date('6/3/07', 'MM/DD/RRRR'), 'matt12amazing', 504, 27.45, 66027, 'KS', 1, 0);

INSERT INTO LOAN (AMOUNT, LOAN_DATE, LOAN_TITLE, RISK_SCORE, DEBT_TO_INCOME_RATIO, ZIPCODE, STATE, EMPLOYMENT_LENGTH, POLICY_CODE) 
VALUES (1500, to_date('6/4/07', 'MM/DD/RRRR'), 'dEs', 711, 58.8, 30327, 'GA', 1, 0);

INSERT INTO LOAN (AMOUNT, LOAN_DATE, LOAN_TITLE, RISK_SCORE, DEBT_TO_INCOME_RATIO, ZIPCODE, STATE, EMPLOYMENT_LENGTH, POLICY_CODE) 
VALUES (1000, to_date('6/4/07', 'MM/DD/RRRR'), 'I''m trying to repair my credit by paying off some old debts.', 530, 8.51, 72227, 'AR', 1, 0);

INSERT INTO LOAN (AMOUNT, LOAN_DATE, LOAN_TITLE, RISK_SCORE, DEBT_TO_INCOME_RATIO, ZIPCODE, STATE, EMPLOYMENT_LENGTH, POLICY_CODE) 
VALUES (7000, to_date('6/4/07', 'MM/DD/RRRR'), 'jd2427', 473, 23.96, 30027, 'GA', 1, 0);

INSERT INTO LOAN (AMOUNT, LOAN_DATE, LOAN_TITLE, RISK_SCORE, DEBT_TO_INCOME_RATIO, ZIPCODE, STATE, EMPLOYMENT_LENGTH, POLICY_CODE) 
VALUES (25000, to_date('6/4/07', 'MM/DD/RRRR'), 'Annieb6283', 606, 4.9, 19127, 'PA', 1, 0);

INSERT INTO LOAN (AMOUNT, LOAN_DATE, LOAN_TITLE, RISK_SCORE, DEBT_TO_INCOME_RATIO, ZIPCODE, STATE, EMPLOYMENT_LENGTH, POLICY_CODE) 
VALUES (10000, to_date('6/4/07', 'MM/DD/RRRR'), 'LenaPresley', 502, 0, 28227, 'NC', 1, 0);

INSERT INTO LOAN (AMOUNT, LOAN_DATE, LOAN_TITLE, RISK_SCORE, DEBT_TO_INCOME_RATIO, ZIPCODE, STATE, EMPLOYMENT_LENGTH, POLICY_CODE) 
VALUES (4000, to_date('6/4/07', 'MM/DD/RRRR'), 'bhissam', 497, 9.87, 26127, 'WV', 1, 0);

INSERT INTO LOAN (AMOUNT, LOAN_DATE, LOAN_TITLE, RISK_SCORE, DEBT_TO_INCOME_RATIO, ZIPCODE, STATE, EMPLOYMENT_LENGTH, POLICY_CODE) 
VALUES (2500, to_date('6/4/07', 'MM/DD/RRRR'), 'Jonelle''s Study Abroad', 709, 10, 11227, 'NY', 1, 0);

INSERT INTO LOAN (AMOUNT, LOAN_DATE, LOAN_TITLE, RISK_SCORE, DEBT_TO_INCOME_RATIO, ZIPCODE, STATE, EMPLOYMENT_LENGTH, POLICY_CODE) 
VALUES (3000, to_date('6/4/07', 'MM/DD/RRRR'), 'belle54304', 412, 20.01, 54327, 'WI', 1, 0);

INSERT INTO LOAN (AMOUNT, LOAN_DATE, LOAN_TITLE, RISK_SCORE, DEBT_TO_INCOME_RATIO, ZIPCODE, STATE, EMPLOYMENT_LENGTH, POLICY_CODE) 
VALUES (1000, to_date('6/4/07', 'MM/DD/RRRR'), 'KB143', 506, 13.01, 37227, 'TN', 3, 0);

INSERT INTO LOAN (AMOUNT, LOAN_DATE, LOAN_TITLE, RISK_SCORE, DEBT_TO_INCOME_RATIO, ZIPCODE, STATE, EMPLOYMENT_LENGTH, POLICY_CODE) 
VALUES (7500, to_date('6/4/07', 'MM/DD/RRRR'), 'fsallustio', 472, 14.36, 2127, 'MA', 7, 0);

INSERT INTO LOAN (AMOUNT, LOAN_DATE, LOAN_TITLE, RISK_SCORE, DEBT_TO_INCOME_RATIO, ZIPCODE, STATE, EMPLOYMENT_LENGTH, POLICY_CODE) 
VALUES (2000, to_date('6/4/07', 'MM/DD/RRRR'), 'mlishuslymotvatd', 507, 0, 13727, 'NY', 1, 0);

INSERT INTO LOAN (AMOUNT, LOAN_DATE, LOAN_TITLE, RISK_SCORE, DEBT_TO_INCOME_RATIO, ZIPCODE, STATE, EMPLOYMENT_LENGTH, POLICY_CODE) 
VALUES (1000, to_date('6/4/07', 'MM/DD/RRRR'), 'Gballgamer', 567, 16.58, 80527, 'CO', 1, 0);

INSERT INTO LOAN (AMOUNT, LOAN_DATE, LOAN_TITLE, RISK_SCORE, DEBT_TO_INCOME_RATIO, ZIPCODE, STATE, EMPLOYMENT_LENGTH, POLICY_CODE) 
VALUES (1100, to_date('6/4/07', 'MM/DD/RRRR'), 'MATTHEW', 551, 0.72, 33427, 'FL', 4, 0);

INSERT INTO LOAN (AMOUNT, LOAN_DATE, LOAN_TITLE, RISK_SCORE, DEBT_TO_INCOME_RATIO, ZIPCODE, STATE, EMPLOYMENT_LENGTH, POLICY_CODE) 
VALUES (3000, to_date('6/4/07', 'MM/DD/RRRR'), 'saxman6160', 0, 4.05, 80027, 'CO', 1, 0);

INSERT INTO LOAN (AMOUNT, LOAN_DATE, LOAN_TITLE, RISK_SCORE, DEBT_TO_INCOME_RATIO, ZIPCODE, STATE, EMPLOYMENT_LENGTH, POLICY_CODE) 
VALUES (1000, to_date('6/5/07', 'MM/DD/RRRR'), 'queenlurline', 0, 0.86, 84627, 'UT', 1, 0);

INSERT INTO LOAN (AMOUNT, LOAN_DATE, LOAN_TITLE, RISK_SCORE, DEBT_TO_INCOME_RATIO, ZIPCODE, STATE, EMPLOYMENT_LENGTH, POLICY_CODE) 
VALUES (7000, to_date('6/5/07', 'MM/DD/RRRR'), 'chrisw1025', 607, 39.79, 27827, 'NC', 2, 0);

INSERT INTO LOAN (AMOUNT, LOAN_DATE, LOAN_TITLE, RISK_SCORE, DEBT_TO_INCOME_RATIO, ZIPCODE, STATE, EMPLOYMENT_LENGTH, POLICY_CODE) 
VALUES (1000, to_date('6/5/07', 'MM/DD/RRRR'), 'ErikBell', 0, 6.55, 80027, 'CO', 4, 0);

INSERT INTO LOAN (AMOUNT, LOAN_DATE, LOAN_TITLE, RISK_SCORE, DEBT_TO_INCOME_RATIO, ZIPCODE, STATE, EMPLOYMENT_LENGTH, POLICY_CODE) 
VALUES (5000, to_date('6/5/07', 'MM/DD/RRRR'), 'baileykearns', 552, 1.6, 45027, 'OH', 2, 0);

INSERT INTO LOAN (AMOUNT, LOAN_DATE, LOAN_TITLE, RISK_SCORE, DEBT_TO_INCOME_RATIO, ZIPCODE, STATE, EMPLOYMENT_LENGTH, POLICY_CODE) 
VALUES (1300, to_date('6/5/07', 'MM/DD/RRRR'), 'kimbbarr', 643, 22.5, 8527, 'NJ', 2, 0);

INSERT INTO LOAN (AMOUNT, LOAN_DATE, LOAN_TITLE, RISK_SCORE, DEBT_TO_INCOME_RATIO, ZIPCODE, STATE, EMPLOYMENT_LENGTH, POLICY_CODE) 
VALUES (500, to_date('6/5/07', 'MM/DD/RRRR'), 'Kiana_Noelle', 547, 18.52, 20727, 'MD', 4, 0);

INSERT INTO LOAN (AMOUNT, LOAN_DATE, LOAN_TITLE, RISK_SCORE, DEBT_TO_INCOME_RATIO, ZIPCODE, STATE, EMPLOYMENT_LENGTH, POLICY_CODE) 
VALUES (1000, to_date('6/5/07', 'MM/DD/RRRR'), 'Raistlan', 647, 7.21, 98027, 'WA', 7, 0);

INSERT INTO LOAN (AMOUNT, LOAN_DATE, LOAN_TITLE, RISK_SCORE, DEBT_TO_INCOME_RATIO, ZIPCODE, STATE, EMPLOYMENT_LENGTH, POLICY_CODE) 
VALUES (1000, to_date('6/5/07', 'MM/DD/RRRR'), 'chynadoll3586', 531, 493.6, 48027, 'AL', 1, 0);

INSERT INTO LOAN (AMOUNT, LOAN_DATE, LOAN_TITLE, RISK_SCORE, DEBT_TO_INCOME_RATIO, ZIPCODE, STATE, EMPLOYMENT_LENGTH, POLICY_CODE) 
VALUES (3000, to_date('6/6/07', 'MM/DD/RRRR'), 'Keith24601', 612, 6.72, 8127, 'NJ', 1, 0);

INSERT INTO LOAN (AMOUNT, LOAN_DATE, LOAN_TITLE, RISK_SCORE, DEBT_TO_INCOME_RATIO, ZIPCODE, STATE, EMPLOYMENT_LENGTH, POLICY_CODE) 
VALUES (2000, to_date('6/6/07', 'MM/DD/RRRR'), 'nicole38', 656, 5.51, 21227, 'MD', 1, 0);

INSERT INTO LOAN (AMOUNT, LOAN_DATE, LOAN_TITLE, RISK_SCORE, DEBT_TO_INCOME_RATIO, ZIPCODE, STATE, EMPLOYMENT_LENGTH, POLICY_CODE) 
VALUES (5000, to_date('6/6/07', 'MM/DD/RRRR'), 'Butterfly', 528, 18.4, 23627, 'VA', 2, 0);

INSERT INTO LOAN (AMOUNT, LOAN_DATE, LOAN_TITLE, RISK_SCORE, DEBT_TO_INCOME_RATIO, ZIPCODE, STATE, EMPLOYMENT_LENGTH, POLICY_CODE) 
VALUES (2000, to_date('6/6/07', 'MM/DD/RRRR'), 'speedy079', 558, 10.85, 8527, 'NJ', 1, 0);

INSERT INTO LOAN (AMOUNT, LOAN_DATE, LOAN_TITLE, RISK_SCORE, DEBT_TO_INCOME_RATIO, ZIPCODE, STATE, EMPLOYMENT_LENGTH, POLICY_CODE) 
VALUES (10000, to_date('6/6/07', 'MM/DD/RRRR'), 'demarishargett', 461, 14.76, 28327, 'NC', 3, 0);

INSERT INTO LOAN (AMOUNT, LOAN_DATE, LOAN_TITLE, RISK_SCORE, DEBT_TO_INCOME_RATIO, ZIPCODE, STATE, EMPLOYMENT_LENGTH, POLICY_CODE) 
VALUES (6700, to_date('6/6/07', 'MM/DD/RRRR'), 'LoveLearn', 522, 4.17, 30227, 'GA', 2, 0);

INSERT INTO LOAN (AMOUNT, LOAN_DATE, LOAN_TITLE, RISK_SCORE, DEBT_TO_INCOME_RATIO, ZIPCODE, STATE, EMPLOYMENT_LENGTH, POLICY_CODE) 
VALUES (20000, to_date('6/6/07', 'MM/DD/RRRR'), 'Back To School', 690, 0.4, 7927, 'NJ', 1, 0);

INSERT INTO LOAN (AMOUNT, LOAN_DATE, LOAN_TITLE, RISK_SCORE, DEBT_TO_INCOME_RATIO, ZIPCODE, STATE, EMPLOYMENT_LENGTH, POLICY_CODE) 
VALUES (3400, to_date('6/6/07', 'MM/DD/RRRR'), 'scooterodell', 559, 24.36, 14527, 'NY', 9, 0);

INSERT INTO LOAN (AMOUNT, LOAN_DATE, LOAN_TITLE, RISK_SCORE, DEBT_TO_INCOME_RATIO, ZIPCODE, STATE, EMPLOYMENT_LENGTH, POLICY_CODE) 
VALUES (5000, to_date('6/6/07', 'MM/DD/RRRR'), 'crazymacguy', 633, 13.03, 53927, 'WI', 1, 0);

INSERT INTO LOAN (AMOUNT, LOAN_DATE, LOAN_TITLE, RISK_SCORE, DEBT_TO_INCOME_RATIO, ZIPCODE, STATE, EMPLOYMENT_LENGTH, POLICY_CODE) 
VALUES (8000, to_date('6/6/07', 'MM/DD/RRRR'), 'TheresaF', 481, 12.21, 44127, 'OH', 1, 0);

INSERT INTO LOAN (AMOUNT, LOAN_DATE, LOAN_TITLE, RISK_SCORE, DEBT_TO_INCOME_RATIO, ZIPCODE, STATE, EMPLOYMENT_LENGTH, POLICY_CODE) 
VALUES (6000, to_date('6/7/07', 'MM/DD/RRRR'), 'tjudith', 679, 26.07, 23227, 'VA', 1, 0);

INSERT INTO LOAN (AMOUNT, LOAN_DATE, LOAN_TITLE, RISK_SCORE, DEBT_TO_INCOME_RATIO, ZIPCODE, STATE, EMPLOYMENT_LENGTH, POLICY_CODE) 
VALUES (5000, to_date('6/8/07', 'MM/DD/RRRR'), '1OTH-MOUNTAIN-MAN', 494, 5.86, 13627, 'NY', 1, 0);

INSERT INTO LOAN (AMOUNT, LOAN_DATE, LOAN_TITLE, RISK_SCORE, DEBT_TO_INCOME_RATIO, ZIPCODE, STATE, EMPLOYMENT_LENGTH, POLICY_CODE) 
VALUES (9500, to_date('6/8/07', 'MM/DD/RRRR'), 'moneywise', 582, 1.47, 99827, 'AK', 1, 0);

INSERT INTO LOAN (AMOUNT, LOAN_DATE, LOAN_TITLE, RISK_SCORE, DEBT_TO_INCOME_RATIO, ZIPCODE, STATE, EMPLOYMENT_LENGTH, POLICY_CODE) 
VALUES (3500, to_date('6/8/07', 'MM/DD/RRRR'), 'tmsworld', 583, 3.12, 10027, 'NY', 1, 0);

INSERT INTO LOAN (AMOUNT, LOAN_DATE, LOAN_TITLE, RISK_SCORE, DEBT_TO_INCOME_RATIO, ZIPCODE, STATE, EMPLOYMENT_LENGTH, POLICY_CODE) 
VALUES (1500, to_date('6/8/07', 'MM/DD/RRRR'), 'Sapphieangel008', 468, 3.98, 45227, 'OH', 1, 0);

INSERT INTO LOAN (AMOUNT, LOAN_DATE, LOAN_TITLE, RISK_SCORE, DEBT_TO_INCOME_RATIO, ZIPCODE, STATE, EMPLOYMENT_LENGTH, POLICY_CODE) 
VALUES (10000, to_date('6/8/07', 'MM/DD/RRRR'), 'FSUgirl', 565, 6.48, 32327, 'FL', 1, 0);

INSERT INTO LOAN (AMOUNT, LOAN_DATE, LOAN_TITLE, RISK_SCORE, DEBT_TO_INCOME_RATIO, ZIPCODE, STATE, EMPLOYMENT_LENGTH, POLICY_CODE) 
VALUES (10000, to_date('6/8/07', 'MM/DD/RRRR'), 'GRNGLD08', 576, 46.15, 23327, 'VA', 1, 0);

INSERT INTO LOAN (AMOUNT, LOAN_DATE, LOAN_TITLE, RISK_SCORE, DEBT_TO_INCOME_RATIO, ZIPCODE, STATE, EMPLOYMENT_LENGTH, POLICY_CODE) 
VALUES (800, to_date('6/8/07', 'MM/DD/RRRR'), 'mozizzle86', 696, 24, 11227, 'NY', 1, 0);

INSERT INTO LOAN (AMOUNT, LOAN_DATE, LOAN_TITLE, RISK_SCORE, DEBT_TO_INCOME_RATIO, ZIPCODE, STATE, EMPLOYMENT_LENGTH, POLICY_CODE) 
VALUES (10000, to_date('6/8/07', 'MM/DD/RRRR'), 'brianmikalw', 559, 0, 13627, 'NY', 1, 0);

INSERT INTO LOAN (AMOUNT, LOAN_DATE, LOAN_TITLE, RISK_SCORE, DEBT_TO_INCOME_RATIO, ZIPCODE, STATE, EMPLOYMENT_LENGTH, POLICY_CODE) 
VALUES (5000, to_date('6/8/07', 'MM/DD/RRRR'), 'thephotoguy.seth', 545, 10.18, 33727, 'TN', 1, 0);

INSERT INTO LOAN (AMOUNT, LOAN_DATE, LOAN_TITLE, RISK_SCORE, DEBT_TO_INCOME_RATIO, ZIPCODE, STATE, EMPLOYMENT_LENGTH, POLICY_CODE) 
VALUES (6000, to_date('6/8/07', 'MM/DD/RRRR'), 'Chase', 602, 2.36, 35427, 'AL', 1, 0);

INSERT INTO LOAN (AMOUNT, LOAN_DATE, LOAN_TITLE, RISK_SCORE, DEBT_TO_INCOME_RATIO, ZIPCODE, STATE, EMPLOYMENT_LENGTH, POLICY_CODE) 
VALUES (1000, to_date('6/8/07', 'MM/DD/RRRR'), 'sgeorges86', 626, 3, 29227, 'SC', 1, 0);

INSERT INTO LOAN (AMOUNT, LOAN_DATE, LOAN_TITLE, RISK_SCORE, DEBT_TO_INCOME_RATIO, ZIPCODE, STATE, EMPLOYMENT_LENGTH, POLICY_CODE) 
VALUES (1000, to_date('6/8/07', 'MM/DD/RRRR'), 'meep737', 640, 5.51, 43027, 'OH', 1, 0);

INSERT INTO LOAN (AMOUNT, LOAN_DATE, LOAN_TITLE, RISK_SCORE, DEBT_TO_INCOME_RATIO, ZIPCODE, STATE, EMPLOYMENT_LENGTH, POLICY_CODE) 
VALUES (15000, to_date('6/9/07', 'MM/DD/RRRR'), 'laurel', 528, 34.27, 13627, 'NY', 1, 0);

INSERT INTO LOAN (AMOUNT, LOAN_DATE, LOAN_TITLE, RISK_SCORE, DEBT_TO_INCOME_RATIO, ZIPCODE, STATE, EMPLOYMENT_LENGTH, POLICY_CODE) 
VALUES (2500, to_date('6/9/07', 'MM/DD/RRRR'), 'kyrstyn', 509, 14.16, 17127, 'PA', 1, 0);

INSERT INTO LOAN (AMOUNT, LOAN_DATE, LOAN_TITLE, RISK_SCORE, DEBT_TO_INCOME_RATIO, ZIPCODE, STATE, EMPLOYMENT_LENGTH, POLICY_CODE) 
VALUES (16000, to_date('6/9/07', 'MM/DD/RRRR'), 'Eagle8XC Tuition loan', 667, 22.98, 5627, 'VT', 1, 0);

INSERT INTO LOAN (AMOUNT, LOAN_DATE, LOAN_TITLE, RISK_SCORE, DEBT_TO_INCOME_RATIO, ZIPCODE, STATE, EMPLOYMENT_LENGTH, POLICY_CODE) 
VALUES (2000, to_date('6/9/07', 'MM/DD/RRRR'), 'Emmyboo0569', 607, 6.91, 23827, 'VA', 1, 0);

INSERT INTO LOAN (AMOUNT, LOAN_DATE, LOAN_TITLE, RISK_SCORE, DEBT_TO_INCOME_RATIO, ZIPCODE, STATE, EMPLOYMENT_LENGTH, POLICY_CODE) 
VALUES (4000, to_date('6/9/07', 'MM/DD/RRRR'), 'jweme', 609, 14.5, 32827, 'FL', 1, 0);

INSERT INTO LOAN (AMOUNT, LOAN_DATE, LOAN_TITLE, RISK_SCORE, DEBT_TO_INCOME_RATIO, ZIPCODE, STATE, EMPLOYMENT_LENGTH, POLICY_CODE) 
VALUES (2000, to_date('6/9/07', 'MM/DD/RRRR'), 'Bizounce', 450, 14.34, 55427, 'MN', 1, 0);

INSERT INTO LOAN (AMOUNT, LOAN_DATE, LOAN_TITLE, RISK_SCORE, DEBT_TO_INCOME_RATIO, ZIPCODE, STATE, EMPLOYMENT_LENGTH, POLICY_CODE) 
VALUES (3000, to_date('6/9/07', 'MM/DD/RRRR'), 'lmhsfan', 0, 9.26, 80527, 'CO', 1, 0);

INSERT INTO LOAN (AMOUNT, LOAN_DATE, LOAN_TITLE, RISK_SCORE, DEBT_TO_INCOME_RATIO, ZIPCODE, STATE, EMPLOYMENT_LENGTH, POLICY_CODE) 
VALUES (6000, to_date('6/9/07', 'MM/DD/RRRR'), 'Chuck Ave', 492, 12, 64127, 'MO', 1, 0);

INSERT INTO LOAN (AMOUNT, LOAN_DATE, LOAN_TITLE, RISK_SCORE, DEBT_TO_INCOME_RATIO, ZIPCODE, STATE, EMPLOYMENT_LENGTH, POLICY_CODE) 
VALUES (2500, to_date('6/10/07', 'MM/DD/RRRR'), 'RebelGrad07', 549, 21.94, 38827, 'MS', 7, 0);

INSERT INTO LOAN (AMOUNT, LOAN_DATE, LOAN_TITLE, RISK_SCORE, DEBT_TO_INCOME_RATIO, ZIPCODE, STATE, EMPLOYMENT_LENGTH, POLICY_CODE) 
VALUES (3000, to_date('6/10/07', 'MM/DD/RRRR'), 'mtalty', 481, 60.11, 46227, 'IN', 3, 0);

INSERT INTO LOAN (AMOUNT, LOAN_DATE, LOAN_TITLE, RISK_SCORE, DEBT_TO_INCOME_RATIO, ZIPCODE, STATE, EMPLOYMENT_LENGTH, POLICY_CODE) 
VALUES (6000, to_date('6/10/07', 'MM/DD/RRRR'), 'brint', 716, 4042.11, 75227, 'TX', 1, 0);

INSERT INTO LOAN (AMOUNT, LOAN_DATE, LOAN_TITLE, RISK_SCORE, DEBT_TO_INCOME_RATIO, ZIPCODE, STATE, EMPLOYMENT_LENGTH, POLICY_CODE) 
VALUES (17000, to_date('6/10/07', 'MM/DD/RRRR'), 'Consolidating credit cards', 653, 5.96, 21227, 'MD', 4, 0);

INSERT INTO LOAN (AMOUNT, LOAN_DATE, LOAN_TITLE, RISK_SCORE, DEBT_TO_INCOME_RATIO, ZIPCODE, STATE, EMPLOYMENT_LENGTH, POLICY_CODE) 
VALUES (5000, to_date('6/10/07', 'MM/DD/RRRR'), 'jedurs', 621, 2.6, 23127, 'VA', 1, 0);

INSERT INTO LOAN (AMOUNT, LOAN_DATE, LOAN_TITLE, RISK_SCORE, DEBT_TO_INCOME_RATIO, ZIPCODE, STATE, EMPLOYMENT_LENGTH, POLICY_CODE) 
VALUES (7500, to_date('6/10/07', 'MM/DD/RRRR'), 'Charles', 629, 45.95, 32227, 'FL', 6, 0);

INSERT INTO LOAN (AMOUNT, LOAN_DATE, LOAN_TITLE, RISK_SCORE, DEBT_TO_INCOME_RATIO, ZIPCODE, STATE, EMPLOYMENT_LENGTH, POLICY_CODE) 
VALUES (15000, to_date('6/11/07', 'MM/DD/RRRR'), 'vervec', 615, 15, 2427, 'MA', 8, 0);

INSERT INTO LOAN (AMOUNT, LOAN_DATE, LOAN_TITLE, RISK_SCORE, DEBT_TO_INCOME_RATIO, ZIPCODE, STATE, EMPLOYMENT_LENGTH, POLICY_CODE) 
VALUES (4000, to_date('6/11/07', 'MM/DD/RRRR'), 'Debt Consolidation', 608, 0, 55827, 'MN', 1, 0);

INSERT INTO LOAN (AMOUNT, LOAN_DATE, LOAN_TITLE, RISK_SCORE, DEBT_TO_INCOME_RATIO, ZIPCODE, STATE, EMPLOYMENT_LENGTH, POLICY_CODE) 
VALUES (4000, to_date('6/11/07', 'MM/DD/RRRR'), 'Nickolae3', 628, 6.36, 40327, 'KY', 1, 0);

INSERT INTO LOAN (AMOUNT, LOAN_DATE, LOAN_TITLE, RISK_SCORE, DEBT_TO_INCOME_RATIO, ZIPCODE, STATE, EMPLOYMENT_LENGTH, POLICY_CODE) 
VALUES (1000, to_date('6/11/07', 'MM/DD/RRRR'), 'Alison', 585, 24, 80327, 'CO', 1, 0);

INSERT INTO LOAN (AMOUNT, LOAN_DATE, LOAN_TITLE, RISK_SCORE, DEBT_TO_INCOME_RATIO, ZIPCODE, STATE, EMPLOYMENT_LENGTH, POLICY_CODE) 
VALUES (1500, to_date('6/11/07', 'MM/DD/RRRR'), 'jaja9487', 493, 6.4, 45727, 'OH', 1, 0);

INSERT INTO LOAN (AMOUNT, LOAN_DATE, LOAN_TITLE, RISK_SCORE, DEBT_TO_INCOME_RATIO, ZIPCODE, STATE, EMPLOYMENT_LENGTH, POLICY_CODE) 
VALUES (6500, to_date('6/11/07', 'MM/DD/RRRR'), 'Sammy', 512, 1.84, 2127, 'MA', 9, 0);

INSERT INTO LOAN (AMOUNT, LOAN_DATE, LOAN_TITLE, RISK_SCORE, DEBT_TO_INCOME_RATIO, ZIPCODE, STATE, EMPLOYMENT_LENGTH, POLICY_CODE) 
VALUES (5000, to_date('6/11/07', 'MM/DD/RRRR'), 'Mattd', 598, 24.7, 30027, 'GA', 1, 0);

INSERT INTO LOAN (AMOUNT, LOAN_DATE, LOAN_TITLE, RISK_SCORE, DEBT_TO_INCOME_RATIO, ZIPCODE, STATE, EMPLOYMENT_LENGTH, POLICY_CODE) 
VALUES (4000, to_date('6/11/07', 'MM/DD/RRRR'), 'mattwalker', 490, 36.92, 23527, 'VA', 4, 0);

INSERT INTO LOAN (AMOUNT, LOAN_DATE, LOAN_TITLE, RISK_SCORE, DEBT_TO_INCOME_RATIO, ZIPCODE, STATE, EMPLOYMENT_LENGTH, POLICY_CODE) 
VALUES (1500, to_date('6/11/07', 'MM/DD/RRRR'), 'nfields1', 588, 9.23, 39527, 'MS', 1, 0);



    
SELECT count(*) FROM Loan;
    
    
    
    
